version: '3.3'

services:
  chatbot-payments-service-deployer:
    build:
      context: ./
      dockerfile: ./Dockerfile-deployer
    container_name: chatbot-payments-container-deployer
    privileged: true
    volumes:
      - /etc/passwd:/etc/passwd
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app
