apiVersion: v1
kind: ConfigMap
metadata:
  name: stripe-payment-config
data:
  application.properties: |
    spring.application.name=ms-payment-stripe
    spring.datasource.url=jdbc:postgresql://stripe-payment-db:5432/sales_db
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.show-sql=true
    server.port=8080
    springdoc.swagger-ui.url=/api-docs.yaml
    springdoc.api-docs.path=/api-docs
    logging.level.root=INFO
    logging.level.com.ebitware=DEBUG
    logging.level.org.springframework=INFO
    management.endpoints.web.exposure.include=*