apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe-payment-db
  template:
    metadata:
      labels:
        app: stripe-payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sales_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: stripe-payment-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stripe-payment-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stripe-payment-db
spec:
  ports:
    - port: 5432
  selector:
    app: stripe-payment-db