apiVersion: v1
kind: Secret
metadata:
  name: stripe-payment-secrets
type: Opaque
data:
  # These are base64 encoded values
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: MTIzNGFiY2Q=  # 1234abcd
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVFlaVdRUUwwT092bDBLUVgzQ1hTTENZZXVZOW8xbE1nT09JTlJyVEdkZ1JoZkMwZjdSMkdtTmhDUFZJUEw1ZjdPMFd0bmRZUzhTRnJrMGVIck05RENPazAwdFpLa0VOQg==